language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

allow_failures:
  php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --no-progress || composer remove --dev friendsofphp/php-cs-fixer --no-interaction --no-progress

script:
  - composer validate --strict
  - vendor/bin/phpstan analyze -c phpstan.neon -l max src
  - vendor/bin/phpcs src tests
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
